server:
  port: ${PORT}
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db.changelog-master.yaml
springdotenv:
  enabled: true